### ISSUE TITLE
otherHalberdierF.png Smudge Error

### ISSUE THREAD

**Issue by heroed** [rainlash/lex-talionis#4]
This looks like a really cool project, but I'm having trouble getting it to run, because every time I try to pull it I encounter this Smudge Error. Is there a way around this?

[20170527T221902.855312log.txt](https://github.com/rainlash/lex-talionis/files/1033922/20170527T221902.855312log.txt)

**Comment by rainlash** [comment]
Hey! 
The error you are getting is caused by Git LFS. I was using Git LFS to handle the large asset files, but I stopped using Git LFS this past weekend. Its not very stable, as you discovered yourself. Most assets are now handled by basic Git.

You can try cloning the project again. You won't need Git LFS anymore. However, you will need to download the Audio folder from the Dropbox link in the README and place the extracted zip in the lex-talionis directory.

**Comment by heroed** [comment]
Thank you so much! It seems to be working now, and I am looking forward to playing the game!
